// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TraderAlgoApi.Data;

#nullable disable

namespace TraderAlgoApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260617024011_AddTradeAccountPnl")]
    partial class AddTradeAccountPnl
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TraderAlgoApi.Models.Backtest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("CandleCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("FinalBalance")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)");

                    b.Property<DateTimeOffset>("From")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("InitialBalance")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)");

                    b.Property<int>("IntervalId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Pnl")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer");

                    b.Property<int>("SymbolId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("To")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("TradeBotId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("IntervalId");

                    b.HasIndex("StatusId");

                    b.HasIndex("SymbolId");

                    b.HasIndex("TradeBotId");

                    b.ToTable("backtests");
                });

            modelBuilder.Entity("TraderAlgoApi.Models.Interval", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("interval");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("intervals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "1m",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayName = "1 Minute",
                            Duration = new TimeSpan(0, 0, 1, 0, 0),
                            IsActive = true,
                            IsDefault = false
                        },
                        new
                        {
                            Id = 2,
                            Code = "5m",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayName = "5 Minute",
                            Duration = new TimeSpan(0, 0, 5, 0, 0),
                            IsActive = true,
                            IsDefault = false
                        },
                        new
                        {
                            Id = 3,
                            Code = "15m",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayName = "15 Minute",
                            Duration = new TimeSpan(0, 0, 15, 0, 0),
                            IsActive = true,
                            IsDefault = false
                        },
                        new
                        {
                            Id = 4,
                            Code = "1h",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayName = "1H",
                            Duration = new TimeSpan(0, 1, 0, 0, 0),
                            IsActive = true,
                            IsDefault = true
                        },
                        new
                        {
                            Id = 5,
                            Code = "4h",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayName = "4H",
                            Duration = new TimeSpan(0, 4, 0, 0, 0),
                            IsActive = true,
                            IsDefault = false
                        },
                        new
                        {
                            Id = 6,
                            Code = "1d",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayName = "1D",
                            Duration = new TimeSpan(1, 0, 0, 0, 0),
                            IsActive = true,
                            IsDefault = false
                        });
                });

            modelBuilder.Entity("TraderAlgoApi.Models.KlineData", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Close")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)");

                    b.Property<DateTimeOffset>("CloseTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("High")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)");

                    b.Property<int>("IntervalId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Low")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)");

                    b.Property<int>("NumberOfTrades")
                        .HasColumnType("integer");

                    b.Property<decimal>("Open")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)");

                    b.Property<DateTimeOffset>("OpenTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("QuoteAssetVolume")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)");

                    b.Property<int>("SymbolId")
                        .HasColumnType("integer");

                    b.Property<decimal>("TakerBuyBaseAssetVolume")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)");

                    b.Property<decimal>("TakerBuyQuoteAssetVolume")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)");

                    b.Property<decimal>("Volume")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)");

                    b.HasKey("Id");

                    b.HasIndex("IntervalId");

                    b.HasIndex("SymbolId", "IntervalId", "OpenTime")
                        .IsUnique();

                    b.ToTable("kline_data");
                });

            modelBuilder.Entity("TraderAlgoApi.Models.Lookups.BacktestStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.ToTable("backtest_statuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Pending"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Running"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Completed"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Failed"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Cancelled"
                        });
                });

            modelBuilder.Entity("TraderAlgoApi.Models.Lookups.SymbolProvider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.ToTable("symbol_providers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Binance"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Alpaca"
                        });
                });

            modelBuilder.Entity("TraderAlgoApi.Models.Lookups.TradeCloseReason", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.ToTable("trade_close_reasons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Manual"
                        },
                        new
                        {
                            Id = 2,
                            Name = "StopLoss"
                        },
                        new
                        {
                            Id = 3,
                            Name = "TakeProfit"
                        },
                        new
                        {
                            Id = 4,
                            Name = "BotSignal"
                        });
                });

            modelBuilder.Entity("TraderAlgoApi.Models.Lookups.TradeOrderType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.ToTable("trade_order_types");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Market"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Limit"
                        });
                });

            modelBuilder.Entity("TraderAlgoApi.Models.Lookups.TradeSide", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.ToTable("trade_sides");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Buy"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Sell"
                        });
                });

            modelBuilder.Entity("TraderAlgoApi.Models.Lookups.TradeStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.ToTable("trade_statuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Pending"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Active"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Closed"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Cancelled"
                        });
                });

            modelBuilder.Entity("TraderAlgoApi.Models.Lookups.TradingStrategy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.ToTable("trading_strategies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "SMA"
                        },
                        new
                        {
                            Id = 2,
                            Name = "RSI"
                        },
                        new
                        {
                            Id = 3,
                            Name = "MACD"
                        },
                        new
                        {
                            Id = 4,
                            Name = "SMA MACD"
                        });
                });

            modelBuilder.Entity("TraderAlgoApi.Models.Macd", b =>
                {
                    b.Property<long>("KlineDataId")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("Histogram")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)")
                        .HasColumnName("histogram");

                    b.Property<decimal?>("MacdLine")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)")
                        .HasColumnName("macd_line");

                    b.Property<decimal?>("SignalLine")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)")
                        .HasColumnName("signal_line");

                    b.HasKey("KlineDataId");

                    b.ToTable("macd");
                });

            modelBuilder.Entity("TraderAlgoApi.Models.RelativeStrengthIndex", b =>
                {
                    b.Property<long>("KlineDataId")
                        .HasColumnType("bigint");

                    b.Property<bool?>("Divergence")
                        .HasColumnType("boolean")
                        .HasColumnName("divergence");

                    b.Property<decimal?>("Rsi")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)")
                        .HasColumnName("rsi");

                    b.Property<decimal?>("RsiSmooth")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)")
                        .HasColumnName("rsi_smooth");

                    b.HasKey("KlineDataId");

                    b.ToTable("relative_strength_indexes");
                });

            modelBuilder.Entity("TraderAlgoApi.Models.SimpleMovingAverage", b =>
                {
                    b.Property<long>("KlineDataId")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("Sma100")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)")
                        .HasColumnName("sma_100");

                    b.Property<decimal?>("Sma20")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)")
                        .HasColumnName("sma_20");

                    b.HasKey("KlineDataId");

                    b.ToTable("simple_moving_averages");
                });

            modelBuilder.Entity("TraderAlgoApi.Models.Symbol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BaseAsset")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<int>("ProviderId")
                        .HasColumnType("integer");

                    b.Property<string>("QuoteAsset")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("ProviderId");

                    b.ToTable("symbols");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BaseAsset = "BTC",
                            Code = "BTCUSDT",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayName = "BTC/USDT",
                            IsActive = true,
                            IsDefault = true,
                            ProviderId = 1,
                            QuoteAsset = "USDT"
                        },
                        new
                        {
                            Id = 2,
                            BaseAsset = "SPY",
                            Code = "SPY",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayName = "SPY",
                            IsActive = true,
                            IsDefault = false,
                            ProviderId = 2,
                            QuoteAsset = "USD"
                        });
                });

            modelBuilder.Entity("TraderAlgoApi.Models.Trade", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("AccountPnl")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)");

                    b.Property<long?>("BacktestId")
                        .HasColumnType("bigint");

                    b.Property<int?>("CloseReasonId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("ClosedPrice")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("EntryPrice")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)");

                    b.Property<decimal>("Fee")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)");

                    b.Property<int?>("IntervalId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("OpenedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("OrderTypeId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Pnl")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)");

                    b.Property<decimal?>("RequestedPrice")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)");

                    b.Property<int>("SideId")
                        .HasColumnType("integer");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("StopLoss")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)");

                    b.Property<int>("SymbolId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("TakeProfit")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)");

                    b.Property<long?>("TradingAccountId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("BacktestId");

                    b.HasIndex("CloseReasonId");

                    b.HasIndex("IntervalId");

                    b.HasIndex("OrderTypeId");

                    b.HasIndex("SideId");

                    b.HasIndex("StatusId");

                    b.HasIndex("TradingAccountId");

                    b.HasIndex("SymbolId", "StatusId");

                    b.ToTable("trades");
                });

            modelBuilder.Entity("TraderAlgoApi.Models.TradeBot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("BacktestId")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("Breakeven")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("DailyProfitGoal")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)");

                    b.Property<decimal>("Fee")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)");

                    b.Property<int>("IntervalId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsNySessionOnly")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastSignalAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("MaxCandlesPerTrade")
                        .HasColumnType("integer");

                    b.Property<int?>("MaxLossesPerDay")
                        .HasColumnType("integer");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)");

                    b.Property<decimal?>("StopLoss")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)");

                    b.Property<int>("SymbolId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("TakeProfit")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)");

                    b.Property<long?>("TradingAccountId")
                        .HasColumnType("bigint");

                    b.Property<int>("TradingStrategyId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BacktestId")
                        .IsUnique()
                        .HasFilter("\"BacktestId\" IS NOT NULL AND \"IsEnabled\"");

                    b.HasIndex("IntervalId");

                    b.HasIndex("SymbolId");

                    b.HasIndex("TradingAccountId")
                        .IsUnique()
                        .HasFilter("\"TradingAccountId\" IS NOT NULL AND \"IsEnabled\"");

                    b.HasIndex("TradingStrategyId");

                    b.ToTable("trade_bots");
                });

            modelBuilder.Entity("TraderAlgoApi.Models.TradingAccount", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("CurrentBalance")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)");

                    b.Property<decimal>("InitialBalance")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("trading_accounts");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CurrentBalance = 1000m,
                            InitialBalance = 1000m,
                            IsActive = true,
                            Name = "Default"
                        });
                });

            modelBuilder.Entity("TraderAlgoApi.Models.Backtest", b =>
                {
                    b.HasOne("TraderAlgoApi.Models.Interval", "Interval")
                        .WithMany()
                        .HasForeignKey("IntervalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TraderAlgoApi.Models.Lookups.BacktestStatus", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TraderAlgoApi.Models.Symbol", "Symbol")
                        .WithMany()
                        .HasForeignKey("SymbolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TraderAlgoApi.Models.TradeBot", "TradeBot")
                        .WithMany()
                        .HasForeignKey("TradeBotId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Interval");

                    b.Navigation("Status");

                    b.Navigation("Symbol");

                    b.Navigation("TradeBot");
                });

            modelBuilder.Entity("TraderAlgoApi.Models.KlineData", b =>
                {
                    b.HasOne("TraderAlgoApi.Models.Interval", "Interval")
                        .WithMany("Klines")
                        .HasForeignKey("IntervalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TraderAlgoApi.Models.Symbol", "Symbol")
                        .WithMany("Klines")
                        .HasForeignKey("SymbolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Interval");

                    b.Navigation("Symbol");
                });

            modelBuilder.Entity("TraderAlgoApi.Models.Macd", b =>
                {
                    b.HasOne("TraderAlgoApi.Models.KlineData", "KlineData")
                        .WithOne("Macd")
                        .HasForeignKey("TraderAlgoApi.Models.Macd", "KlineDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KlineData");
                });

            modelBuilder.Entity("TraderAlgoApi.Models.RelativeStrengthIndex", b =>
                {
                    b.HasOne("TraderAlgoApi.Models.KlineData", "KlineData")
                        .WithOne("RelativeStrengthIndex")
                        .HasForeignKey("TraderAlgoApi.Models.RelativeStrengthIndex", "KlineDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KlineData");
                });

            modelBuilder.Entity("TraderAlgoApi.Models.SimpleMovingAverage", b =>
                {
                    b.HasOne("TraderAlgoApi.Models.KlineData", "KlineData")
                        .WithOne("SimpleMovingAverage")
                        .HasForeignKey("TraderAlgoApi.Models.SimpleMovingAverage", "KlineDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KlineData");
                });

            modelBuilder.Entity("TraderAlgoApi.Models.Symbol", b =>
                {
                    b.HasOne("TraderAlgoApi.Models.Lookups.SymbolProvider", "Provider")
                        .WithMany()
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("TraderAlgoApi.Models.Trade", b =>
                {
                    b.HasOne("TraderAlgoApi.Models.Backtest", "Backtest")
                        .WithMany("Trades")
                        .HasForeignKey("BacktestId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TraderAlgoApi.Models.Lookups.TradeCloseReason", "CloseReason")
                        .WithMany()
                        .HasForeignKey("CloseReasonId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TraderAlgoApi.Models.Interval", "Interval")
                        .WithMany()
                        .HasForeignKey("IntervalId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TraderAlgoApi.Models.Lookups.TradeOrderType", "OrderType")
                        .WithMany()
                        .HasForeignKey("OrderTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TraderAlgoApi.Models.Lookups.TradeSide", "Side")
                        .WithMany()
                        .HasForeignKey("SideId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TraderAlgoApi.Models.Lookups.TradeStatus", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TraderAlgoApi.Models.Symbol", "Symbol")
                        .WithMany()
                        .HasForeignKey("SymbolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TraderAlgoApi.Models.TradingAccount", "TradingAccount")
                        .WithMany("Trades")
                        .HasForeignKey("TradingAccountId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Backtest");

                    b.Navigation("CloseReason");

                    b.Navigation("Interval");

                    b.Navigation("OrderType");

                    b.Navigation("Side");

                    b.Navigation("Status");

                    b.Navigation("Symbol");

                    b.Navigation("TradingAccount");
                });

            modelBuilder.Entity("TraderAlgoApi.Models.TradeBot", b =>
                {
                    b.HasOne("TraderAlgoApi.Models.Backtest", "Backtest")
                        .WithMany("TradeBots")
                        .HasForeignKey("BacktestId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TraderAlgoApi.Models.Interval", "Interval")
                        .WithMany()
                        .HasForeignKey("IntervalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TraderAlgoApi.Models.Symbol", "Symbol")
                        .WithMany()
                        .HasForeignKey("SymbolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TraderAlgoApi.Models.TradingAccount", "TradingAccount")
                        .WithMany("TradeBots")
                        .HasForeignKey("TradingAccountId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TraderAlgoApi.Models.Lookups.TradingStrategy", "TradingStrategy")
                        .WithMany()
                        .HasForeignKey("TradingStrategyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Backtest");

                    b.Navigation("Interval");

                    b.Navigation("Symbol");

                    b.Navigation("TradingAccount");

                    b.Navigation("TradingStrategy");
                });

            modelBuilder.Entity("TraderAlgoApi.Models.Backtest", b =>
                {
                    b.Navigation("TradeBots");

                    b.Navigation("Trades");
                });

            modelBuilder.Entity("TraderAlgoApi.Models.Interval", b =>
                {
                    b.Navigation("Klines");
                });

            modelBuilder.Entity("TraderAlgoApi.Models.KlineData", b =>
                {
                    b.Navigation("Macd");

                    b.Navigation("RelativeStrengthIndex");

                    b.Navigation("SimpleMovingAverage");
                });

            modelBuilder.Entity("TraderAlgoApi.Models.Symbol", b =>
                {
                    b.Navigation("Klines");
                });

            modelBuilder.Entity("TraderAlgoApi.Models.TradingAccount", b =>
                {
                    b.Navigation("TradeBots");

                    b.Navigation("Trades");
                });
#pragma warning restore 612, 618
        }
    }
}
