// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TraderAlgoApi.Data;

#nullable disable

namespace TraderAlgoApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260505000000_AddMaxCandlesPerTradeToBacktest")]
    partial class AddMaxCandlesPerTradeToBacktest
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TraderAlgoApi.Models.Backtest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("Breakeven")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)");

                    b.Property<decimal?>("DailyProfitGoal")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)");

                    b.Property<bool>("IsNySessionOnly")
                        .HasColumnType("boolean");

                    b.Property<int?>("MaxCandlesPerTrade")
                        .HasColumnType("integer");

                    b.Property<int?>("MaxLossesPerDay")
                        .HasColumnType("integer");

                    b.Property<int>("CandleCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("FinalBalance")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)");

                    b.Property<DateTimeOffset>("From")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("InitialBalance")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)");

                    b.Property<int>("IntervalId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Pnl")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal?>("StopLoss")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)");

                    b.Property<int>("SymbolId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("TakeProfit")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)");

                    b.Property<DateTimeOffset>("To")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("TradeBotId")
                        .HasColumnType("bigint");

                    b.Property<int>("TradingStrategyId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IntervalId");

                    b.HasIndex("SymbolId");

                    b.HasIndex("TradeBotId");

                    b.HasIndex("TradingStrategyId");

                    b.ToTable("backtests");
                });
#pragma warning restore 612, 618
        }
    }
}
