// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TraderAlgoApi.Data;

#nullable disable

namespace TraderAlgoApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260416171646_AddFiveMinuteInterval")]
    partial class AddFiveMinuteInterval
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TraderAlgoApi.Models.Interval", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("interval");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("intervals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "1h",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayName = "1H",
                            Duration = new TimeSpan(0, 1, 0, 0, 0),
                            IsActive = true
                        },
                        new
                        {
                            Id = 2,
                            Code = "5m",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayName = "5 Minute",
                            Duration = new TimeSpan(0, 0, 5, 0, 0),
                            IsActive = true
                        });
                });

            modelBuilder.Entity("TraderAlgoApi.Models.KlineData", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Close")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)");

                    b.Property<DateTimeOffset>("CloseTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("High")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)");

                    b.Property<int>("IntervalId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Low")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)");

                    b.Property<int>("NumberOfTrades")
                        .HasColumnType("integer");

                    b.Property<decimal>("Open")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)");

                    b.Property<DateTimeOffset>("OpenTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("QuoteAssetVolume")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)");

                    b.Property<int>("SymbolId")
                        .HasColumnType("integer");

                    b.Property<decimal>("TakerBuyBaseAssetVolume")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)");

                    b.Property<decimal>("TakerBuyQuoteAssetVolume")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)");

                    b.Property<decimal>("Volume")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)");

                    b.HasKey("Id");

                    b.HasIndex("IntervalId");

                    b.HasIndex("SymbolId", "IntervalId", "OpenTime")
                        .IsUnique();

                    b.ToTable("kline_data");
                });

            modelBuilder.Entity("TraderAlgoApi.Models.Symbol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BaseAsset")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("QuoteAsset")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("symbols");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BaseAsset = "BTC",
                            Code = "BTCUSD",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayName = "BTC/USD",
                            IsActive = true,
                            QuoteAsset = "USD"
                        });
                });

            modelBuilder.Entity("TraderAlgoApi.Models.KlineData", b =>
                {
                    b.HasOne("TraderAlgoApi.Models.Interval", "Interval")
                        .WithMany("Klines")
                        .HasForeignKey("IntervalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TraderAlgoApi.Models.Symbol", "Symbol")
                        .WithMany("Klines")
                        .HasForeignKey("SymbolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Interval");

                    b.Navigation("Symbol");
                });

            modelBuilder.Entity("TraderAlgoApi.Models.Interval", b =>
                {
                    b.Navigation("Klines");
                });

            modelBuilder.Entity("TraderAlgoApi.Models.Symbol", b =>
                {
                    b.Navigation("Klines");
                });
#pragma warning restore 612, 618
        }
    }
}
