// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TraderAlgoApi.Data;

#nullable disable

namespace TraderAlgoApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260708113101_DropMlPolicyTuningHyperparameters")]
    partial class DropMlPolicyTuningHyperparameters
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TraderAlgoApi.Models.Atr", b =>
                {
                    b.Property<long>("KlineDataId")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("AtrValue")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)")
                        .HasColumnName("atr");

                    b.Property<int>("Period")
                        .HasColumnType("integer")
                        .HasColumnName("period");

                    b.Property<decimal?>("TrueRange")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)")
                        .HasColumnName("true_range");

                    b.HasKey("KlineDataId");

                    b.ToTable("atr");
                });

            modelBuilder.Entity("TraderAlgoApi.Models.Backtest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("CandleCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("FinalBalance")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)");

                    b.Property<DateTimeOffset>("From")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("InitialBalance")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)");

                    b.Property<int>("IntervalId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Pnl")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer");

                    b.Property<int>("SymbolId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("To")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("TradeBotId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("IntervalId");

                    b.HasIndex("StatusId");

                    b.HasIndex("SymbolId");

                    b.HasIndex("TradeBotId");

                    b.ToTable("backtests");
                });

            modelBuilder.Entity("TraderAlgoApi.Models.Interval", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("interval");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("intervals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "1m",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayName = "1 Minute",
                            Duration = new TimeSpan(0, 0, 1, 0, 0),
                            IsActive = true,
                            IsDefault = false
                        },
                        new
                        {
                            Id = 2,
                            Code = "5m",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayName = "5 Minute",
                            Duration = new TimeSpan(0, 0, 5, 0, 0),
                            IsActive = true,
                            IsDefault = false
                        },
                        new
                        {
                            Id = 3,
                            Code = "15m",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayName = "15 Minute",
                            Duration = new TimeSpan(0, 0, 15, 0, 0),
                            IsActive = true,
                            IsDefault = false
                        },
                        new
                        {
                            Id = 4,
                            Code = "1h",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayName = "1H",
                            Duration = new TimeSpan(0, 1, 0, 0, 0),
                            IsActive = true,
                            IsDefault = true
                        },
                        new
                        {
                            Id = 5,
                            Code = "4h",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayName = "4H",
                            Duration = new TimeSpan(0, 4, 0, 0, 0),
                            IsActive = true,
                            IsDefault = false
                        },
                        new
                        {
                            Id = 6,
                            Code = "1d",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayName = "1D",
                            Duration = new TimeSpan(1, 0, 0, 0, 0),
                            IsActive = true,
                            IsDefault = false
                        });
                });

            modelBuilder.Entity("TraderAlgoApi.Models.KlineData", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Close")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)");

                    b.Property<DateTimeOffset>("CloseTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("High")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)");

                    b.Property<int>("IntervalId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Low")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)");

                    b.Property<int>("NumberOfTrades")
                        .HasColumnType("integer");

                    b.Property<decimal>("Open")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)");

                    b.Property<DateTimeOffset>("OpenTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("QuoteAssetVolume")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)");

                    b.Property<int>("SymbolId")
                        .HasColumnType("integer");

                    b.Property<decimal>("TakerBuyBaseAssetVolume")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)");

                    b.Property<decimal>("TakerBuyQuoteAssetVolume")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)");

                    b.Property<decimal>("Volume")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)");

                    b.HasKey("Id");

                    b.HasIndex("IntervalId");

                    b.HasIndex("SymbolId", "IntervalId", "OpenTime")
                        .IsUnique();

                    b.ToTable("kline_data");
                });

            modelBuilder.Entity("TraderAlgoApi.Models.Lookups.BacktestStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.ToTable("backtest_statuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Pending"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Running"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Completed"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Failed"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Cancelled"
                        });
                });

            modelBuilder.Entity("TraderAlgoApi.Models.Lookups.MlTrainingRunStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.ToTable("ml_training_run_statuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Pending"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Running"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Completed"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Failed"
                        });
                });

            modelBuilder.Entity("TraderAlgoApi.Models.Lookups.SymbolProvider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.ToTable("symbol_providers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Binance"
                        });
                });

            modelBuilder.Entity("TraderAlgoApi.Models.Lookups.SyncJobStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.ToTable("sync_job_statuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Pending"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Running"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Completed"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Failed"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Cancelled"
                        });
                });

            modelBuilder.Entity("TraderAlgoApi.Models.Lookups.SyncJobType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("Id");

                    b.ToTable("sync_job_types");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "DataCollectorFullSync"
                        },
                        new
                        {
                            Id = 2,
                            Name = "DataCollectorPartialSync"
                        },
                        new
                        {
                            Id = 3,
                            Name = "IndicatorFullSync"
                        },
                        new
                        {
                            Id = 4,
                            Name = "IndicatorPartialSync"
                        });
                });

            modelBuilder.Entity("TraderAlgoApi.Models.Lookups.TradeCloseReason", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.ToTable("trade_close_reasons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Manual"
                        },
                        new
                        {
                            Id = 2,
                            Name = "StopLoss"
                        },
                        new
                        {
                            Id = 3,
                            Name = "TakeProfit"
                        },
                        new
                        {
                            Id = 4,
                            Name = "BotSignal"
                        });
                });

            modelBuilder.Entity("TraderAlgoApi.Models.Lookups.TradeOrderType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.ToTable("trade_order_types");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Market"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Limit"
                        });
                });

            modelBuilder.Entity("TraderAlgoApi.Models.Lookups.TradeSide", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.ToTable("trade_sides");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Buy"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Sell"
                        });
                });

            modelBuilder.Entity("TraderAlgoApi.Models.Lookups.TradeStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.ToTable("trade_statuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Pending"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Active"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Closed"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Cancelled"
                        });
                });

            modelBuilder.Entity("TraderAlgoApi.Models.Lookups.TradingStrategy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.ToTable("trading_strategies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "SMA"
                        },
                        new
                        {
                            Id = 2,
                            Name = "RSI"
                        },
                        new
                        {
                            Id = 3,
                            Name = "MACD"
                        },
                        new
                        {
                            Id = 4,
                            Name = "SMA MACD"
                        },
                        new
                        {
                            Id = 5,
                            Name = "ML Policy"
                        });
                });

            modelBuilder.Entity("TraderAlgoApi.Models.Macd", b =>
                {
                    b.Property<long>("KlineDataId")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("Histogram")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)")
                        .HasColumnName("histogram");

                    b.Property<decimal?>("MacdLine")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)")
                        .HasColumnName("macd_line");

                    b.Property<decimal?>("SignalLine")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)")
                        .HasColumnName("signal_line");

                    b.HasKey("KlineDataId");

                    b.ToTable("macd");
                });

            modelBuilder.Entity("TraderAlgoApi.Models.MlPolicy", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Breakeven")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)");

                    b.Property<decimal>("BreakevenStop")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("DailyDrawdownLimit")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)");

                    b.Property<decimal>("DailyProfit")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)");

                    b.Property<decimal>("Fee")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)");

                    b.Property<decimal>("InitialBalance")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)");

                    b.Property<int>("IntervalId")
                        .HasColumnType("integer");

                    b.Property<int>("MaxCandlesPerTrade")
                        .HasColumnType("integer");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)");

                    b.Property<decimal?>("RiskPerTrade")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)");

                    b.Property<decimal>("Slippage")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)");

                    b.Property<int>("SymbolId")
                        .HasColumnType("integer");

                    b.Property<int>("TotalTimesteps")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IntervalId");

                    b.HasIndex("SymbolId");

                    b.ToTable("ml_policies");
                });

            modelBuilder.Entity("TraderAlgoApi.Models.MlTrainingRun", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("FinalBalance")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)");

                    b.Property<decimal?>("FinalBalanceOos")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)");

                    b.Property<DateTimeOffset>("From")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("MlPolicyId")
                        .HasColumnType("bigint");

                    b.Property<int?>("NTrades")
                        .HasColumnType("integer");

                    b.Property<decimal?>("PnlPct")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)");

                    b.Property<decimal?>("PnlPctOos")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)");

                    b.Property<string>("RunId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("To")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MlPolicyId");

                    b.HasIndex("StatusId");

                    b.ToTable("ml_training_runs");
                });

            modelBuilder.Entity("TraderAlgoApi.Models.RelativeStrengthIndex", b =>
                {
                    b.Property<long>("KlineDataId")
                        .HasColumnType("bigint");

                    b.Property<bool?>("Divergence")
                        .HasColumnType("boolean")
                        .HasColumnName("divergence");

                    b.Property<decimal?>("Rsi")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)")
                        .HasColumnName("rsi");

                    b.Property<decimal?>("RsiSmooth")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)")
                        .HasColumnName("rsi_smooth");

                    b.HasKey("KlineDataId");

                    b.ToTable("relative_strength_indexes");
                });

            modelBuilder.Entity("TraderAlgoApi.Models.SimpleMovingAverage", b =>
                {
                    b.Property<long>("KlineDataId")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("Sma100")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)")
                        .HasColumnName("sma_100");

                    b.Property<decimal?>("Sma20")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)")
                        .HasColumnName("sma_20");

                    b.HasKey("KlineDataId");

                    b.ToTable("simple_moving_averages");
                });

            modelBuilder.Entity("TraderAlgoApi.Models.Symbol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BaseAsset")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<int>("ProviderId")
                        .HasColumnType("integer");

                    b.Property<string>("QuoteAsset")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("ProviderId");

                    b.ToTable("symbols");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BaseAsset = "BTC",
                            Code = "BTCUSDT",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayName = "BTC/USDT",
                            IsActive = true,
                            IsDefault = true,
                            ProviderId = 1,
                            QuoteAsset = "USDT"
                        },
                        new
                        {
                            Id = 3,
                            BaseAsset = "ETH",
                            Code = "ETHUSDT",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayName = "ETH/USDT",
                            IsActive = true,
                            IsDefault = false,
                            ProviderId = 1,
                            QuoteAsset = "USDT"
                        });
                });

            modelBuilder.Entity("TraderAlgoApi.Models.SyncJob", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CompletedUnits")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Error")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Message")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer");

                    b.Property<int>("TotalUnits")
                        .HasColumnType("integer");

                    b.Property<int>("TypeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StatusId");

                    b.HasIndex("TypeId");

                    b.ToTable("sync_jobs");
                });

            modelBuilder.Entity("TraderAlgoApi.Models.SyncJobError", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("CandleOpenTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Interval")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<long>("SyncJobId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("SyncJobId");

                    b.HasIndex("Symbol", "Interval", "CandleOpenTime");

                    b.ToTable("sync_job_errors");
                });

            modelBuilder.Entity("TraderAlgoApi.Models.Telemetry.TrainingChartArtifact", b =>
                {
                    b.Property<string>("RunId")
                        .HasColumnType("text")
                        .HasColumnName("run_id");

                    b.Property<string>("ChartKey")
                        .HasColumnType("text")
                        .HasColumnName("chart_key");

                    b.Property<string>("ContentType")
                        .HasColumnType("text")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Kind")
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<string>("StoragePath")
                        .HasColumnType("text")
                        .HasColumnName("storage_path");

                    b.HasKey("RunId", "ChartKey");

                    b.ToTable("training_chart_artifacts");
                });

            modelBuilder.Entity("TraderAlgoApi.Models.Telemetry.TrainingCheckpointEval", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool?>("Eligible")
                        .HasColumnType("boolean")
                        .HasColumnName("eligible");

                    b.Property<double?>("Gap")
                        .HasColumnType("double precision")
                        .HasColumnName("gap");

                    b.Property<bool?>("IsBest")
                        .HasColumnType("boolean")
                        .HasColumnName("is_best");

                    b.Property<double?>("QTrain")
                        .HasColumnType("double precision")
                        .HasColumnName("q_train");

                    b.Property<double?>("QVal")
                        .HasColumnType("double precision")
                        .HasColumnName("q_val");

                    b.Property<string>("RunId")
                        .HasColumnType("text")
                        .HasColumnName("run_id");

                    b.Property<double?>("Score")
                        .HasColumnType("double precision")
                        .HasColumnName("score");

                    b.Property<int?>("Timesteps")
                        .HasColumnType("integer")
                        .HasColumnName("timesteps");

                    b.Property<double?>("TrainDdPct")
                        .HasColumnType("double precision")
                        .HasColumnName("train_dd_pct");

                    b.Property<double?>("TrainEvalR")
                        .HasColumnType("double precision")
                        .HasColumnName("train_eval_r");

                    b.Property<double?>("ValDdPct")
                        .HasColumnType("double precision")
                        .HasColumnName("val_dd_pct");

                    b.Property<double?>("ValR")
                        .HasColumnType("double precision")
                        .HasColumnName("val_r");

                    b.HasKey("Id");

                    b.HasIndex("RunId", "Timesteps");

                    b.ToTable("training_checkpoint_evals");
                });

            modelBuilder.Entity("TraderAlgoApi.Models.Telemetry.TrainingDecisionLog", b =>
                {
                    b.Property<string>("RunId")
                        .HasColumnType("text")
                        .HasColumnName("run_id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.HasKey("RunId");

                    b.ToTable("training_decisions");
                });

            modelBuilder.Entity("TraderAlgoApi.Models.Telemetry.TrainingEquityPoint", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double?>("DrawdownPct")
                        .HasColumnType("double precision")
                        .HasColumnName("drawdown_pct");

                    b.Property<double?>("Equity")
                        .HasColumnType("double precision")
                        .HasColumnName("equity");

                    b.Property<int?>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<double?>("RealizedPnl")
                        .HasColumnType("double precision")
                        .HasColumnName("realized_pnl");

                    b.Property<string>("RunId")
                        .HasColumnType("text")
                        .HasColumnName("run_id");

                    b.Property<string>("Split")
                        .HasColumnType("text")
                        .HasColumnName("split");

                    b.Property<long?>("Ts")
                        .HasColumnType("bigint")
                        .HasColumnName("ts");

                    b.HasKey("Id");

                    b.HasIndex("RunId", "Split", "Ts");

                    b.ToTable("training_equity_points");
                });

            modelBuilder.Entity("TraderAlgoApi.Models.Telemetry.TrainingFeatureQuality", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double?>("Cv")
                        .HasColumnType("double precision")
                        .HasColumnName("cv");

                    b.Property<double?>("ExcessKurt")
                        .HasColumnType("double precision")
                        .HasColumnName("excess_kurt");

                    b.Property<string>("Feature")
                        .HasColumnType("text")
                        .HasColumnName("feature");

                    b.Property<double?>("Mean")
                        .HasColumnType("double precision")
                        .HasColumnName("mean");

                    b.Property<string>("RunId")
                        .HasColumnType("text")
                        .HasColumnName("run_id");

                    b.Property<bool?>("SignalP05")
                        .HasColumnType("boolean")
                        .HasColumnName("signal_p05");

                    b.Property<double?>("Skew")
                        .HasColumnType("double precision")
                        .HasColumnName("skew");

                    b.Property<double?>("SpearmanP1Bar")
                        .HasColumnType("double precision")
                        .HasColumnName("spearman_p_1bar");

                    b.Property<double?>("SpearmanR1Bar")
                        .HasColumnType("double precision")
                        .HasColumnName("spearman_r_1bar");

                    b.Property<double?>("Std")
                        .HasColumnType("double precision")
                        .HasColumnName("std");

                    b.HasKey("Id");

                    b.HasIndex("RunId", "Feature");

                    b.ToTable("training_feature_quality");
                });

            modelBuilder.Entity("TraderAlgoApi.Models.Telemetry.TrainingFoldResult", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double?>("AvgR")
                        .HasColumnType("double precision")
                        .HasColumnName("avg_r");

                    b.Property<int?>("Fold")
                        .HasColumnType("integer")
                        .HasColumnName("fold");

                    b.Property<bool?>("IsOos")
                        .HasColumnType("boolean")
                        .HasColumnName("is_oos");

                    b.Property<double?>("MaxDdPct")
                        .HasColumnType("double precision")
                        .HasColumnName("max_dd_pct");

                    b.Property<int?>("NTrades")
                        .HasColumnType("integer")
                        .HasColumnName("n_trades");

                    b.Property<double?>("ProfitFactor")
                        .HasColumnType("double precision")
                        .HasColumnName("profit_factor");

                    b.Property<double?>("ReturnPct")
                        .HasColumnType("double precision")
                        .HasColumnName("return_pct");

                    b.Property<string>("RunId")
                        .HasColumnType("text")
                        .HasColumnName("run_id");

                    b.Property<string>("Scheme")
                        .HasColumnType("text")
                        .HasColumnName("scheme");

                    b.Property<double?>("Sharpe")
                        .HasColumnType("double precision")
                        .HasColumnName("sharpe");

                    b.Property<string>("TestEnd")
                        .HasColumnType("text")
                        .HasColumnName("test_end");

                    b.Property<string>("TestStart")
                        .HasColumnType("text")
                        .HasColumnName("test_start");

                    b.Property<string>("TrainEnd")
                        .HasColumnType("text")
                        .HasColumnName("train_end");

                    b.Property<string>("TrainStart")
                        .HasColumnType("text")
                        .HasColumnName("train_start");

                    b.Property<string>("ValEnd")
                        .HasColumnType("text")
                        .HasColumnName("val_end");

                    b.Property<string>("ValStart")
                        .HasColumnType("text")
                        .HasColumnName("val_start");

                    b.Property<double?>("WinRatePct")
                        .HasColumnType("double precision")
                        .HasColumnName("win_rate_pct");

                    b.HasKey("Id");

                    b.HasIndex("RunId", "Fold");

                    b.ToTable("training_fold_results");
                });

            modelBuilder.Entity("TraderAlgoApi.Models.Telemetry.TrainingLearningCurve", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double?>("MeanEpLength")
                        .HasColumnType("double precision")
                        .HasColumnName("mean_ep_length");

                    b.Property<double?>("MeanEpReward")
                        .HasColumnType("double precision")
                        .HasColumnName("mean_ep_reward");

                    b.Property<string>("RunId")
                        .HasColumnType("text")
                        .HasColumnName("run_id");

                    b.Property<double?>("StdEpReward")
                        .HasColumnType("double precision")
                        .HasColumnName("std_ep_reward");

                    b.Property<int?>("Timesteps")
                        .HasColumnType("integer")
                        .HasColumnName("timesteps");

                    b.HasKey("Id");

                    b.HasIndex("RunId", "Timesteps");

                    b.ToTable("training_learning_curve");
                });

            modelBuilder.Entity("TraderAlgoApi.Models.Telemetry.TrainingRunPerformance", b =>
                {
                    b.Property<string>("RunId")
                        .HasColumnType("text")
                        .HasColumnName("run_id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("FromDate")
                        .HasColumnType("text")
                        .HasColumnName("from_date");

                    b.Property<string>("GateDetail")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("gate_detail")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<bool?>("GatePassed")
                        .HasColumnType("boolean")
                        .HasColumnName("gate_passed");

                    b.Property<double?>("InSampleMinusOosPnlPct")
                        .HasColumnType("double precision")
                        .HasColumnName("in_sample_minus_oos_pnl_pct");

                    b.Property<double?>("InSamplePnlPct")
                        .HasColumnType("double precision")
                        .HasColumnName("in_sample_pnl_pct");

                    b.Property<int?>("MlPolicyId")
                        .HasColumnType("integer")
                        .HasColumnName("ml_policy_id");

                    b.Property<int?>("NFolds")
                        .HasColumnType("integer")
                        .HasColumnName("n_folds");

                    b.Property<int?>("ObsDim")
                        .HasColumnType("integer")
                        .HasColumnName("obs_dim");

                    b.Property<double?>("OosMaxDdPct")
                        .HasColumnType("double precision")
                        .HasColumnName("oos_max_dd_pct");

                    b.Property<double?>("OosPnlPct")
                        .HasColumnType("double precision")
                        .HasColumnName("oos_pnl_pct");

                    b.Property<double?>("OosProfitFactor")
                        .HasColumnType("double precision")
                        .HasColumnName("oos_profit_factor");

                    b.Property<double?>("OosSharpe")
                        .HasColumnType("double precision")
                        .HasColumnName("oos_sharpe");

                    b.Property<bool?>("Promoted")
                        .HasColumnType("boolean")
                        .HasColumnName("promoted");

                    b.Property<int?>("SchemaVersion")
                        .HasColumnType("integer")
                        .HasColumnName("schema_version");

                    b.Property<string>("Scheme")
                        .HasColumnType("text")
                        .HasColumnName("scheme");

                    b.Property<int?>("Seed")
                        .HasColumnType("integer")
                        .HasColumnName("seed");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("ToDate")
                        .HasColumnType("text")
                        .HasColumnName("to_date");

                    b.HasKey("RunId");

                    b.HasIndex("MlPolicyId", "CreatedAt");

                    b.ToTable("training_run_performance");
                });

            modelBuilder.Entity("TraderAlgoApi.Models.Telemetry.TrainingSplitMetrics", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double?>("AnnualizedReturnPct")
                        .HasColumnType("double precision")
                        .HasColumnName("annualized_return_pct");

                    b.Property<double?>("AvgR")
                        .HasColumnType("double precision")
                        .HasColumnName("avg_r");

                    b.Property<double?>("CalmarRatio")
                        .HasColumnType("double precision")
                        .HasColumnName("calmar_ratio");

                    b.Property<double?>("MaxDrawdownPct")
                        .HasColumnType("double precision")
                        .HasColumnName("max_drawdown_pct");

                    b.Property<int?>("NTrades")
                        .HasColumnType("integer")
                        .HasColumnName("n_trades");

                    b.Property<double?>("ProfitFactor")
                        .HasColumnType("double precision")
                        .HasColumnName("profit_factor");

                    b.Property<string>("RunId")
                        .HasColumnType("text")
                        .HasColumnName("run_id");

                    b.Property<double?>("SharpeLike")
                        .HasColumnType("double precision")
                        .HasColumnName("sharpe_like");

                    b.Property<double?>("SortinoRatio")
                        .HasColumnType("double precision")
                        .HasColumnName("sortino_ratio");

                    b.Property<string>("Split")
                        .HasColumnType("text")
                        .HasColumnName("split");

                    b.Property<double?>("TotalReturnPct")
                        .HasColumnType("double precision")
                        .HasColumnName("total_return_pct");

                    b.Property<double?>("WinRatePct")
                        .HasColumnType("double precision")
                        .HasColumnName("win_rate_pct");

                    b.HasKey("Id");

                    b.HasIndex("RunId", "Split");

                    b.ToTable("training_split_metrics");
                });

            modelBuilder.Entity("TraderAlgoApi.Models.Telemetry.TrainingTrade", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int?>("BarsInTrade")
                        .HasColumnType("integer")
                        .HasColumnName("bars_in_trade");

                    b.Property<string>("Direction")
                        .HasColumnType("text")
                        .HasColumnName("direction");

                    b.Property<double?>("EntryPrice")
                        .HasColumnType("double precision")
                        .HasColumnName("entry_price");

                    b.Property<long?>("EntryTime")
                        .HasColumnType("bigint")
                        .HasColumnName("entry_time");

                    b.Property<double?>("ExitPrice")
                        .HasColumnType("double precision")
                        .HasColumnName("exit_price");

                    b.Property<string>("ExitReason")
                        .HasColumnType("text")
                        .HasColumnName("exit_reason");

                    b.Property<long?>("ExitTime")
                        .HasColumnType("bigint")
                        .HasColumnName("exit_time");

                    b.Property<double?>("Pnl")
                        .HasColumnType("double precision")
                        .HasColumnName("pnl");

                    b.Property<double?>("RMult")
                        .HasColumnType("double precision")
                        .HasColumnName("r_mult");

                    b.Property<string>("RunId")
                        .HasColumnType("text")
                        .HasColumnName("run_id");

                    b.Property<double?>("Sl")
                        .HasColumnType("double precision")
                        .HasColumnName("sl");

                    b.Property<double?>("SlAtrMult")
                        .HasColumnType("double precision")
                        .HasColumnName("sl_atr_mult");

                    b.Property<string>("Split")
                        .HasColumnType("text")
                        .HasColumnName("split");

                    b.Property<double?>("Tp")
                        .HasColumnType("double precision")
                        .HasColumnName("tp");

                    b.Property<double?>("TpRBracket")
                        .HasColumnType("double precision")
                        .HasColumnName("tp_r_bracket");

                    b.Property<double?>("Units")
                        .HasColumnType("double precision")
                        .HasColumnName("units");

                    b.HasKey("Id");

                    b.HasIndex("RunId", "Split", "EntryTime");

                    b.ToTable("training_trades");
                });

            modelBuilder.Entity("TraderAlgoApi.Models.Trade", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("AccountPnl")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)");

                    b.Property<decimal?>("AtrAtEntry")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)");

                    b.Property<long?>("BacktestId")
                        .HasColumnType("bigint");

                    b.Property<int?>("CloseReasonId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("ClosedPrice")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("EntryPrice")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)");

                    b.Property<decimal>("Fee")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)");

                    b.Property<int?>("IntervalId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("OpenedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("OrderTypeId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Pnl")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)");

                    b.Property<decimal?>("RequestedPrice")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)");

                    b.Property<int>("SideId")
                        .HasColumnType("integer");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("StopLoss")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)");

                    b.Property<int>("SymbolId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("TakeProfit")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)");

                    b.Property<long?>("TradingAccountId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("BacktestId");

                    b.HasIndex("CloseReasonId");

                    b.HasIndex("IntervalId");

                    b.HasIndex("OrderTypeId");

                    b.HasIndex("SideId");

                    b.HasIndex("StatusId");

                    b.HasIndex("TradingAccountId");

                    b.HasIndex("SymbolId", "StatusId");

                    b.ToTable("trades");
                });

            modelBuilder.Entity("TraderAlgoApi.Models.TradeBot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("BacktestId")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("Breakeven")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)");

                    b.Property<decimal?>("BreakevenStop")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("DailyProfitGoal")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)");

                    b.Property<bool>("Delay")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Fee")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)");

                    b.Property<int>("IntervalId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsNySessionOnly")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastSignalAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("MaxCandlesPerTrade")
                        .HasColumnType("integer");

                    b.Property<int?>("MaxLossesPerDay")
                        .HasColumnType("integer");

                    b.Property<long?>("MlPolicyId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)");

                    b.Property<decimal?>("StopLoss")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)");

                    b.Property<int>("SymbolId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("TakeProfit")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)");

                    b.Property<long?>("TradingAccountId")
                        .HasColumnType("bigint");

                    b.Property<int>("TradingStrategyId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BacktestId")
                        .IsUnique()
                        .HasFilter("\"BacktestId\" IS NOT NULL AND \"IsEnabled\"");

                    b.HasIndex("IntervalId");

                    b.HasIndex("MlPolicyId");

                    b.HasIndex("SymbolId");

                    b.HasIndex("TradingAccountId")
                        .IsUnique()
                        .HasFilter("\"TradingAccountId\" IS NOT NULL AND \"IsEnabled\"");

                    b.HasIndex("TradingStrategyId");

                    b.ToTable("trade_bots");
                });

            modelBuilder.Entity("TraderAlgoApi.Models.TradingAccount", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("CurrentBalance")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)");

                    b.Property<decimal>("InitialBalance")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("trading_accounts");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CurrentBalance = 1000m,
                            InitialBalance = 1000m,
                            IsActive = true,
                            Name = "Default"
                        });
                });

            modelBuilder.Entity("TraderAlgoApi.Models.Atr", b =>
                {
                    b.HasOne("TraderAlgoApi.Models.KlineData", "KlineData")
                        .WithOne("Atr")
                        .HasForeignKey("TraderAlgoApi.Models.Atr", "KlineDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KlineData");
                });

            modelBuilder.Entity("TraderAlgoApi.Models.Backtest", b =>
                {
                    b.HasOne("TraderAlgoApi.Models.Interval", "Interval")
                        .WithMany()
                        .HasForeignKey("IntervalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TraderAlgoApi.Models.Lookups.BacktestStatus", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TraderAlgoApi.Models.Symbol", "Symbol")
                        .WithMany()
                        .HasForeignKey("SymbolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TraderAlgoApi.Models.TradeBot", "TradeBot")
                        .WithMany()
                        .HasForeignKey("TradeBotId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Interval");

                    b.Navigation("Status");

                    b.Navigation("Symbol");

                    b.Navigation("TradeBot");
                });

            modelBuilder.Entity("TraderAlgoApi.Models.KlineData", b =>
                {
                    b.HasOne("TraderAlgoApi.Models.Interval", "Interval")
                        .WithMany("Klines")
                        .HasForeignKey("IntervalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TraderAlgoApi.Models.Symbol", "Symbol")
                        .WithMany("Klines")
                        .HasForeignKey("SymbolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Interval");

                    b.Navigation("Symbol");
                });

            modelBuilder.Entity("TraderAlgoApi.Models.Macd", b =>
                {
                    b.HasOne("TraderAlgoApi.Models.KlineData", "KlineData")
                        .WithOne("Macd")
                        .HasForeignKey("TraderAlgoApi.Models.Macd", "KlineDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KlineData");
                });

            modelBuilder.Entity("TraderAlgoApi.Models.MlPolicy", b =>
                {
                    b.HasOne("TraderAlgoApi.Models.Interval", "Interval")
                        .WithMany()
                        .HasForeignKey("IntervalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TraderAlgoApi.Models.Symbol", "Symbol")
                        .WithMany()
                        .HasForeignKey("SymbolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Interval");

                    b.Navigation("Symbol");
                });

            modelBuilder.Entity("TraderAlgoApi.Models.MlTrainingRun", b =>
                {
                    b.HasOne("TraderAlgoApi.Models.MlPolicy", "Policy")
                        .WithMany("TrainingRuns")
                        .HasForeignKey("MlPolicyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TraderAlgoApi.Models.Lookups.MlTrainingRunStatus", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Policy");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("TraderAlgoApi.Models.RelativeStrengthIndex", b =>
                {
                    b.HasOne("TraderAlgoApi.Models.KlineData", "KlineData")
                        .WithOne("RelativeStrengthIndex")
                        .HasForeignKey("TraderAlgoApi.Models.RelativeStrengthIndex", "KlineDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KlineData");
                });

            modelBuilder.Entity("TraderAlgoApi.Models.SimpleMovingAverage", b =>
                {
                    b.HasOne("TraderAlgoApi.Models.KlineData", "KlineData")
                        .WithOne("SimpleMovingAverage")
                        .HasForeignKey("TraderAlgoApi.Models.SimpleMovingAverage", "KlineDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KlineData");
                });

            modelBuilder.Entity("TraderAlgoApi.Models.Symbol", b =>
                {
                    b.HasOne("TraderAlgoApi.Models.Lookups.SymbolProvider", "Provider")
                        .WithMany()
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("TraderAlgoApi.Models.SyncJob", b =>
                {
                    b.HasOne("TraderAlgoApi.Models.Lookups.SyncJobStatus", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TraderAlgoApi.Models.Lookups.SyncJobType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Status");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("TraderAlgoApi.Models.SyncJobError", b =>
                {
                    b.HasOne("TraderAlgoApi.Models.SyncJob", "SyncJob")
                        .WithMany()
                        .HasForeignKey("SyncJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SyncJob");
                });

            modelBuilder.Entity("TraderAlgoApi.Models.Trade", b =>
                {
                    b.HasOne("TraderAlgoApi.Models.Backtest", "Backtest")
                        .WithMany("Trades")
                        .HasForeignKey("BacktestId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TraderAlgoApi.Models.Lookups.TradeCloseReason", "CloseReason")
                        .WithMany()
                        .HasForeignKey("CloseReasonId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TraderAlgoApi.Models.Interval", "Interval")
                        .WithMany()
                        .HasForeignKey("IntervalId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TraderAlgoApi.Models.Lookups.TradeOrderType", "OrderType")
                        .WithMany()
                        .HasForeignKey("OrderTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TraderAlgoApi.Models.Lookups.TradeSide", "Side")
                        .WithMany()
                        .HasForeignKey("SideId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TraderAlgoApi.Models.Lookups.TradeStatus", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TraderAlgoApi.Models.Symbol", "Symbol")
                        .WithMany()
                        .HasForeignKey("SymbolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TraderAlgoApi.Models.TradingAccount", "TradingAccount")
                        .WithMany("Trades")
                        .HasForeignKey("TradingAccountId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Backtest");

                    b.Navigation("CloseReason");

                    b.Navigation("Interval");

                    b.Navigation("OrderType");

                    b.Navigation("Side");

                    b.Navigation("Status");

                    b.Navigation("Symbol");

                    b.Navigation("TradingAccount");
                });

            modelBuilder.Entity("TraderAlgoApi.Models.TradeBot", b =>
                {
                    b.HasOne("TraderAlgoApi.Models.Backtest", "Backtest")
                        .WithMany("TradeBots")
                        .HasForeignKey("BacktestId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TraderAlgoApi.Models.Interval", "Interval")
                        .WithMany()
                        .HasForeignKey("IntervalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TraderAlgoApi.Models.MlPolicy", "MlPolicy")
                        .WithMany("TradeBots")
                        .HasForeignKey("MlPolicyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TraderAlgoApi.Models.Symbol", "Symbol")
                        .WithMany()
                        .HasForeignKey("SymbolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TraderAlgoApi.Models.TradingAccount", "TradingAccount")
                        .WithMany("TradeBots")
                        .HasForeignKey("TradingAccountId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TraderAlgoApi.Models.Lookups.TradingStrategy", "TradingStrategy")
                        .WithMany()
                        .HasForeignKey("TradingStrategyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Backtest");

                    b.Navigation("Interval");

                    b.Navigation("MlPolicy");

                    b.Navigation("Symbol");

                    b.Navigation("TradingAccount");

                    b.Navigation("TradingStrategy");
                });

            modelBuilder.Entity("TraderAlgoApi.Models.Backtest", b =>
                {
                    b.Navigation("TradeBots");

                    b.Navigation("Trades");
                });

            modelBuilder.Entity("TraderAlgoApi.Models.Interval", b =>
                {
                    b.Navigation("Klines");
                });

            modelBuilder.Entity("TraderAlgoApi.Models.KlineData", b =>
                {
                    b.Navigation("Atr");

                    b.Navigation("Macd");

                    b.Navigation("RelativeStrengthIndex");

                    b.Navigation("SimpleMovingAverage");
                });

            modelBuilder.Entity("TraderAlgoApi.Models.MlPolicy", b =>
                {
                    b.Navigation("TradeBots");

                    b.Navigation("TrainingRuns");
                });

            modelBuilder.Entity("TraderAlgoApi.Models.Symbol", b =>
                {
                    b.Navigation("Klines");
                });

            modelBuilder.Entity("TraderAlgoApi.Models.TradingAccount", b =>
                {
                    b.Navigation("TradeBots");

                    b.Navigation("Trades");
                });
#pragma warning restore 612, 618
        }
    }
}
