using System.Text.Json.Serialization;

namespace TraderAlgoApi.Dtos.Ml;

/// <summary>Create/update body for a training policy. Symbol/interval are codes; model is an id.</summary>
public sealed record MlPolicyRequest(
    [property: JsonPropertyName("symbol")]    string Symbol,
    [property: JsonPropertyName("interval")]  string Interval,
    [property: JsonPropertyName("totalTimesteps")]      int TotalTimesteps,
    [property: JsonPropertyName("initialBalance")]      decimal InitialBalance,
    [property: JsonPropertyName("quantity")]            decimal Quantity,
    [property: JsonPropertyName("takeProfit")]          decimal TakeProfit,
    [property: JsonPropertyName("stopLoss")]            decimal StopLoss,
    [property: JsonPropertyName("breakeven")]           decimal Breakeven,
    [property: JsonPropertyName("breakevenStop")]       decimal BreakevenStop,
    [property: JsonPropertyName("fee")]                 decimal Fee,
    [property: JsonPropertyName("slippage")]            decimal Slippage,
    [property: JsonPropertyName("dailyProfit")]         decimal DailyProfit,
    [property: JsonPropertyName("dailyDrawdownLimit")]  decimal DailyDrawdownLimit,
    [property: JsonPropertyName("maxCandlesPerTrade")]  int MaxCandlesPerTrade,
    [property: JsonPropertyName("maxTrailingDrawdown")] decimal MaxTrailingDrawdown,
    // Optional ML tuning parameters (§3). Null = use the ML service default.
    [property: JsonPropertyName("episodeDays")]             double? EpisodeDays = null,
    [property: JsonPropertyName("entryCost")]               double? EntryCost = null,
    [property: JsonPropertyName("noTradeDayPenalty")]       double? NoTradeDayPenalty = null,
    [property: JsonPropertyName("streakBonusCoef")]         double? StreakBonusCoef = null,
    [property: JsonPropertyName("maxStreakBonus")]          double? MaxStreakBonus = null,
    [property: JsonPropertyName("maxPatienceRewardPerDay")] double? MaxPatienceRewardPerDay = null,
    [property: JsonPropertyName("learningRate")]            double? LearningRate = null,
    [property: JsonPropertyName("nSteps")]                  int? NSteps = null,
    [property: JsonPropertyName("batchSize")]               int? BatchSize = null,
    [property: JsonPropertyName("nEpochs")]                 int? NEpochs = null,
    [property: JsonPropertyName("gamma")]                   double? Gamma = null,
    [property: JsonPropertyName("gaeLambda")]               double? GaeLambda = null,
    [property: JsonPropertyName("clipRange")]               double? ClipRange = null,
    [property: JsonPropertyName("entCoef")]                 double? EntCoef = null,
    [property: JsonPropertyName("oosEvalEvery")]            int? OosEvalEvery = null);

public sealed record MlPolicyResponse(
    [property: JsonPropertyName("id")]            long Id,
    [property: JsonPropertyName("symbolId")]      int SymbolId,
    [property: JsonPropertyName("symbolCode")]    string SymbolCode,
    [property: JsonPropertyName("intervalId")]    int IntervalId,
    [property: JsonPropertyName("intervalCode")]  string IntervalCode,
    [property: JsonPropertyName("totalTimesteps")]      int TotalTimesteps,
    [property: JsonPropertyName("initialBalance")]      decimal InitialBalance,
    [property: JsonPropertyName("quantity")]            decimal Quantity,
    [property: JsonPropertyName("takeProfit")]          decimal TakeProfit,
    [property: JsonPropertyName("stopLoss")]            decimal StopLoss,
    [property: JsonPropertyName("breakeven")]           decimal Breakeven,
    [property: JsonPropertyName("breakevenStop")]       decimal BreakevenStop,
    [property: JsonPropertyName("fee")]                 decimal Fee,
    [property: JsonPropertyName("slippage")]            decimal Slippage,
    [property: JsonPropertyName("dailyProfit")]         decimal DailyProfit,
    [property: JsonPropertyName("dailyDrawdownLimit")]  decimal DailyDrawdownLimit,
    [property: JsonPropertyName("maxCandlesPerTrade")]  int MaxCandlesPerTrade,
    [property: JsonPropertyName("maxTrailingDrawdown")] decimal MaxTrailingDrawdown,
    [property: JsonPropertyName("episodeDays")]             double? EpisodeDays,
    [property: JsonPropertyName("entryCost")]               double? EntryCost,
    [property: JsonPropertyName("noTradeDayPenalty")]       double? NoTradeDayPenalty,
    [property: JsonPropertyName("streakBonusCoef")]         double? StreakBonusCoef,
    [property: JsonPropertyName("maxStreakBonus")]          double? MaxStreakBonus,
    [property: JsonPropertyName("maxPatienceRewardPerDay")] double? MaxPatienceRewardPerDay,
    [property: JsonPropertyName("learningRate")]            double? LearningRate,
    [property: JsonPropertyName("nSteps")]                  int? NSteps,
    [property: JsonPropertyName("batchSize")]               int? BatchSize,
    [property: JsonPropertyName("nEpochs")]                 int? NEpochs,
    [property: JsonPropertyName("gamma")]                   double? Gamma,
    [property: JsonPropertyName("gaeLambda")]               double? GaeLambda,
    [property: JsonPropertyName("clipRange")]               double? ClipRange,
    [property: JsonPropertyName("entCoef")]                 double? EntCoef,
    [property: JsonPropertyName("oosEvalEvery")]            int? OosEvalEvery,
    [property: JsonPropertyName("createdAt")]           long CreatedAt,
    [property: JsonPropertyName("trainingRunCount")]    int TrainingRunCount);
